# Quay.io doesn't allow container image & application repositories in the same organization
# to share a name. In this case, the image is quay.io/coreos/alb-ingress-controller,
# and the Helm chart is quay.io/coreos/alb-ingress-controller-helm. This variable
# overrides the chart name.
nameOverride: alb-ingress-controller

## AWS region in which this ingress controller will operate
## REQUIRED
#
awsRegion: us-west-1

## Resources created by the ALB Ingress controller will be prefixed with this string
## REQUIRED
#
clusterName: k8s

controller:
  image:
    repository: quay.io/coreos/alb-ingress-controller
    tag: "0.8"
    pullPolicy: IfNotPresent

  extraEnv: {}
    # AWS_ACCESS_KEY_ID: ""
    # AWS_SECRET_ACCESS_KEY: ""
    # AWS_DEBUG: false
    # DISABLE_ROUTE53: false
    # LOG_LEVEL: ""

  nodeSelector: {}
    # node-role.kubernetes.io/node: "true"
    # tier: cs

  tolerations: {}

  podAnnotations: {}
    # iam.amazonaws.com/role: alb-ingress-controller

  podLabels: {}

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 100Mi
    # requests:
    #   cpu: 100m
    #   memory: 100Mi

  service:
    annotations: {}
      # prometheus.io/scrape: "true"

    labels: {}

defaultBackend:
  image:
    repository: gcr.io/google_containers/defaultbackend
    tag: "1.2"
    pullPolicy: IfNotPresent

  nodeSelector: {}
    # node-role.kubernetes.io/node: "true"
    # tier: cs

  tolerations: {}

  podAnnotations: {}
  podLabels: {}
  replicaCount: 1

  resources: {}
    # limits:
    #   cpu: 10m
    #   memory: 20Mi
    # requests:
    #   cpu: 10m
    #   memory: 20Mi

  service:
    annotations: {}
    labels: {}

rbac:
  ## If true, create & use RBAC resources
  ##
  create: true

  ## Ignored if rbac.create is true
  serviceAccountName: default

scope:
  ## If provided, the ALB ingress controller will only act on Ingress resources annotated with this class
  ## Ref: https://github.com/coreos/alb-ingress-controller/blob/master/docs/configuration.md#limiting-ingress-class
  #
  ingressClass: alb

  ## If true, the ALB ingress controller will only act on Ingress resources in a single namespace
  ## Default: false; watch all namespaces
  #
  singleNamespace: false

  ## If scope.singleNamespace=true, the ALB ingress controller will only act on Ingress resources in this namespace
  ## Ref: https://github.com/coreos/alb-ingress-controller/blob/master/docs/configuration.md#limiting-namespaces
  ## Default: namespace of the ALB ingress controller
  #
  watchNamespace: ""
